root: true
extends: eslint:recommended

env:
  browser: true
  es6: true
  mocha: true
  node: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  # Possible errors.
  no-console: 'off'
  no-empty: [error, {allowEmptyCatch: true}]
  no-extra-parens: error
  no-template-curly-in-string: error
  no-unsafe-negation: error
  valid-jsdoc:
  - error
  - prefer:
      arg: param
      argument: param
      augments: extends
      description: desc
      exception: throws
      fires: emits
      host: external
      prop: property
      returns: return
      virtual: abstract
    preferType:
      Boolean: boolean
      Function: function
      Number: number
      Object: object
      String: string
      Symbol: symbol
    requireReturn: false

  # Best practices.
  array-callback-return: error
  block-scoped-var: error
  consistent-return: error
  curly: [error, multi]
  dot-notation: error
  no-alert: error
  no-caller: error
  no-case-declarations: 'off'
  no-else-return: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-redeclare: [error, {builtinGlobals: true}]
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: 'off'
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  wrap-iife: [error, inside]
  yoda: [error, never]

  # Variables.
  no-catch-shadow: error
  no-undefined: error
  no-use-before-define: [error, {functions: false}]

  # Node.js and CommonJS.
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-sync: error

  # Stylistic issues.
  brace-style: [error, stroustrup, {allowSingleLine: true}]
  camelcase: 'off'
  consistent-this: [error, self]
  indent: [error, 2, {SwitchCase: 1}]
  keyword-spacing: error
  linebreak-style: 'off'
  line-comment-position: error
  new-cap: error
  newline-before-return: 'off'
  no-array-constructor: error
  no-lonely-if: error
  no-mixed-operators: error
  no-multiple-empty-lines: error
  no-new-object: error
  no-tabs: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing: error
  one-var: [error, never]
  operator-assignment: error
  quote-props: [error, as-needed]
  quotes: [error, single]
  require-jsdoc: [error, {require: {ClassDeclaration: true, FunctionDeclaration: true, MethodDefinition: true}}]
  semi: error
  semi-spacing: error
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: [error, {nonwords: false, words: true}]
  spaced-comment: error
  unicode-bom: error

  # ECMAScript 6.
  arrow-body-style: error
  arrow-parens: [error, as-needed]
  arrow-spacing: error
  generator-star-spacing: [error, before]
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: [error, before]
