site_name: Enums for JS
site_description: Prevent comment spam using the Enums service, in JavaScript.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/enum.js

docs_dir: doc
site_dir: web

repo_name: Gitea/Belin.io
repo_url: https://git.belin.io/cedx/enum.js
edit_uri: ''

copyright: Copyright &copy; 2014 - 2018 Cédric Belin
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

extra:
  social:
  - {type: globe, link: 'https://belin.io'}
  - {type: git, link: 'https://git.belin.io/cedx'}
  - {type: twitter, link: 'https://twitter.com/cedxbelin'}
  - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
- admonition
- codehilite
- meta

nav:
- Overview: index.md
- Installation: installation.md
- Usage: usage.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: yellow, accent: yellow}
