name: build
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Check environment
        run: |
          node --version
          npm --version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: npm run coverage
